#!/bin/sh

if test $# = 0 ; then
 set -- 0 1 2 3 4 5 6 7
fi
for i ; do
   mknod /dev/myri$i c 220 `expr $i "*" 2` 2> /dev/null  \
	  && chmod 666 /dev/myri$i
   mknod /dev/myrip$i c 220 `expr $i "*" 2 + 1` 2> /dev/null \
	  && chmod 600 /dev/myrip$i 
done
mknod /dev/myri c 220 254 2> /dev/null \
    && chmod 666 /dev/myri
mknod /dev/myrip c 220 255 2> /dev/null \
    && chmod 600 /dev/myrip
exit 0
